apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  serviceName: {{ .Chart.Name }}-headless
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{- range .Values.imagePullSecrets }}
        - name: {{ . }}
{{- end }}
{{- end }}
      initContainers:
{{ include "initContainers.waitForPostgres" . | indent 8 }}
      priorityClassName: medium-priority
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.image.registry }}/{{ .Values.image }}:{{ .Values.imageTag }}"
          env:
            - name: BASE_DOMAIN
              valueFrom: { configMapKeyRef: { name: {{ .Values.global.domain.configMapName }}, key: BASE_DOMAIN } }
            - name: KEYCLOAK_ADMIN
              valueFrom: { secretKeyRef: { name: {{ include "secrets.authentication.name" . }}, key: KC_ADMIN_LOGIN } }
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom: { secretKeyRef: { name: {{ include "secrets.authentication.name" . }}, key: KC_ADMIN_PASSWORD } }
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME
              value: "https://id.$(BASE_DOMAIN)"
            - name: KC_CACHE_STACK
              value: "kubernetes"
            - name: KC_HOSTNAME_ADMIN
              value: "https://id.$(BASE_DOMAIN)"
            - name: KC_HOSTNAME_DEBUG
              value: "true"
            - name: KC_LOG
              value: "console"
            - name: KC_DB_URL_DATABASE
              value: "keycloak"
            - name: KC_DB_URL_HOST
              valueFrom: { secretKeyRef: { name: {{ .Values.global.database.secretName }}, key: host } }
            - name: KC_DB_URL_PORT
              valueFrom: { secretKeyRef: { name: {{ .Values.global.database.secretName }}, key: port } }
            - name: KC_DB_USERNAME
              valueFrom: { secretKeyRef: { name: {{ .Values.global.database.secretName }}, key: username } }
            - name: KC_DB_PASSWORD
              valueFrom: { secretKeyRef: { name: {{ .Values.global.database.secretName }}, key: password } }
            - name: KC_DB_POOL_MAX_SIZE
              value: {{ .Values.db.poolSize | quote }}
            - name: JAVA_OPTS_APPEND
              value: "-Djgroups.dns.query={{ .Chart.Name }}-headless -Djboss.bind.address=0.0.0.0 -Djboss.bind.address.management=0.0.0.0 -Djboss.bind.address.private=0.0.0.0 -Djboss.management.http.port=9990 -Dkeycloak.profile.feature.metrics=enabled"
            - name: JGROUPS_DISCOVERY_PROTOCOL
              value: "KUBE_PING"
            # The following values are used to configure the number of cache owners for the Infinispan cache
            - name: CACHE_OWNERS_COUNT
              value: {{ .Values.cacheOwnersCount | quote }}
            - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
              value: {{ .Values.cacheOwnersAuthSessionsCount | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 9000
              protocol: TCP
            - name: discovery
              containerPort: 7800
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /health/started
              port: 9000
            initialDelaySeconds: 100
            failureThreshold: 300
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
{{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
